export const BUSINESS_IDEAS = [
    {
      name: "Digital Marketing Agency",
      category: "agency",
      businessType: "B2B",
      description: "Help businesses enhance their online presence through various digital marketing services like SEO, PPC, and social media marketing.",
      startupCost: "$$$",
      difficulty: 3,
      timeCommitment: "30-40 hrs/week",
      speedToRevenue: "1-3 months",
      potentialRevenue: 8500,
      popularityRating: 8,
      profitMargin: 7,
      scalability: 8,
      competition: 3,
      workLifeBalance: 5
    },
    {
      name: "Niche E-commerce Store",
      category: "ecommerce",
      businessType: "B2C",
      description: "Create an online store targeting a specific niche market with curated products or your own specialized merchandise.",
      startupCost: "$$",
      difficulty: 2,
      timeCommitment: "20-30 hrs/week",
      speedToRevenue: "1-3 months",
      potentialRevenue: 6000,
      popularityRating: 7,
      profitMargin: 6,
      scalability: 7,
      competition: 5,
      workLifeBalance: 6
    },
    {
      name: "Micro SaaS Tool",
      category: "saas",
      businessType: "B2B",
      description: "Develop a small, focused software solution that addresses a specific pain point for businesses or professionals.",
      startupCost: "$$$",
      difficulty: 4,
      timeCommitment: "30-40 hrs/week",
      speedToRevenue: "6-12 months",
      potentialRevenue: 15000,
      popularityRating: 9,
      profitMargin: 9,
      scalability: 10,
      competition: 6,
      workLifeBalance: 7
    },
    {
      name: "YouTube Channel",
      category: "content",
      businessType: "B2C",
      description: "Create engaging video content on a specific topic to build an audience and monetize through ads, sponsorships, and product placements.",
      startupCost: "$",
      difficulty: 2,
      timeCommitment: "10-20 hrs/week",
      speedToRevenue: "6-12 months",
      potentialRevenue: 5000,
      popularityRating: 8,
      profitMargin: 8,
      scalability: 6,
      competition: 7,
      workLifeBalance: 8
    },
    {
      name: "Affiliate Marketing Blog",
      category: "affiliate",
      businessType: "B2C",
      description: "Create content that recommends products/services and earn commissions when readers make purchases through your affiliate links.",
      startupCost: "$",
      difficulty: 2,
      timeCommitment: "10-20 hrs/week",
      speedToRevenue: "3-6 months",
      potentialRevenue: 4000,
      popularityRating: 7,
      profitMargin: 9,
      scalability: 7,
      competition: 6,
      workLifeBalance: 9
    },
    {
      name: "Digital Template Shop",
      category: "digital",
      businessType: "B2C/B2B",
      description: "Create and sell digital templates for various purposes - resumes, social media graphics, presentation slides, planners, etc.",
      startupCost: "$$",
      difficulty: 3,
      timeCommitment: "20-30 hrs/week",
      speedToRevenue: "1-3 months",
      potentialRevenue: 7500,
      popularityRating: 8,
      profitMargin: 10,
      scalability: 9,
      competition: 5,
      workLifeBalance: 8
    },
    {
      name: "Online Course Creator",
      category: "education",
      businessType: "B2C",
      description: "Develop and sell educational courses on topics where you have expertise or can provide valuable knowledge.",
      startupCost: "$$",
      difficulty: 3,
      timeCommitment: "20-30 hrs/week",
      speedToRevenue: "3-6 months",
      potentialRevenue: 10000,
      popularityRating: 9,
      profitMargin: 9,
      scalability: 9,
      competition: 7,
      workLifeBalance: 8
    },
    {
      name: "Niche Podcast",
      category: "content",
      businessType: "B2C",
      description: "Create audio content focused on a specific topic or industry and monetize through sponsorships, ads, and premium content.",
      startupCost: "$",
      difficulty: 2,
      timeCommitment: "10-20 hrs/week",
      speedToRevenue: "6-12 months",
      potentialRevenue: 3500,
      popularityRating: 7,
      profitMargin: 7,
      scalability: 6,
      competition: 5,
      workLifeBalance: 8
    },
    {
      name: "Freelance Web Developer",
      category: "services",
      businessType: "B2B",
      description: "Offer web development services to businesses and individuals who need websites, web applications, or custom code.",
      startupCost: "$",
      difficulty: 3,
      timeCommitment: "30-40 hrs/week",
      speedToRevenue: "1-3 months",
      potentialRevenue: 9000,
      popularityRating: 7,
      profitMargin: 8,
      scalability: 5,
      competition: 8,
      workLifeBalance: 6
    }
  ];
  